this.state = {
  objectOrigin: {
    left: "50%",
    top: "50%",
    width: "60px",
    height: "60px",
    position: "fixed",
    color: "red",
  },
  animation: {
    name: "customAnimation",
    duration: "2s",
    timingFunction: "ease-in-out",
    delay: "0s",
    iterationCount: "infinite",
    direction: "alternate",
    fillMode: "forwards",
    playState: "running",
  },
  transform: {
    rotate: "110deg",
    scale: "1.0",
    translate: "0deg, 0deg",
    skew: "0deg, 0deg",
  },
  filter: {
    blur: "0px",
    brightness: "0.0",
    contrast: "0%",
    greyscale: "0%",
    hueRotate: "0deg",
    dropShadow: "0px 0px 0px black",
    invert: "0%",
    opacity: "0%",
    saturate: "0%",
    sepia: "0%",
  },
  keyframes: {
    prct0: {
      enabled: true,
      prct: "0%",
      xAxis: "0",
      yAxis: "0",
      transform: {
        rotate: "110deg",
        scale: "1.0",
        translate: "0deg, 0deg",
        skew: "0deg, 0deg",
      },
      filter: {
        blur: "0px",
        brightness: "0.0",
        contrast: "0%",
        greyscale: "0%",
        hueRotate: "0deg",
        dropShadow: "0px 0px 0px black",
        invert: "0%",
        opacity: "0%",
        saturate: "0%",
        sepia: "0%",
      }
    },
    prct10: {
      emabled: false,
      prct: "10%",
      xAxis: "0",
      yAxis: "0",
      transform: {
        rotate: "110deg",
        scale: "1.0",
        translate: "0deg, 0deg",
        skew: "0deg, 0deg",
      },
      filter: {
        blur: "0px",
        brightness: "0.0",
        contrast: "0%",
        greyscale: "0%",
        hueRotate: "0deg",
        dropShadow: "0px 0px 0px black",
        invert: "0%",
        opacity: "0%",
        saturate: "0%",
        sepia: "0%",
      }
    },
    prct20: {
      emabled: false,
      prct: "20%",
      xAxis: "0",
      yAxis: "0",
      transform: {
        rotate: "110deg",
        scale: "1.0",
        translate: "0deg, 0deg",
        skew: "0deg, 0deg",
      },
      filter: {
        blur: "0px",
        brightness: "0.0",
        contrast: "0%",
        greyscale: "0%",
        hueRotate: "0deg",
        dropShadow: "0px 0px 0px black",
        invert: "0%",
        opacity: "0%",
        saturate: "0%",
        sepia: "0%",
      }
    },
    prct30: {
      emabled: false,
      prct: "30%",
      xAxis: "0",
      yAxis: "0",
      transform: {
        rotate: "110deg",
        scale: "1.0",
        translate: "0deg, 0deg",
        skew: "0deg, 0deg",
      },
      filter: {
        blur: "0px",
        brightness: "0.0",
        contrast: "0%",
        greyscale: "0%",
        hueRotate: "0deg",
        dropShadow: "0px 0px 0px black",
        invert: "0%",
        opacity: "0%",
        saturate: "0%",
        sepia: "0%",
      }
    },
    prct40: {
      emabled: false,
      prct: "40%",
      xAxis: "0",
      yAxis: "0",
      transform: {
        rotate: "110deg",
        scale: "1.0",
        translate: "0deg, 0deg",
        skew: "0deg, 0deg",
      },
      filter: {
        blur: "0px",
        brightness: "0.0",
        contrast: "0%",
        greyscale: "0%",
        hueRotate: "0deg",
        dropShadow: "0px 0px 0px black",
        invert: "0%",
        opacity: "0%",
        saturate: "0%",
        sepia: "0%",
      }
    },
    prct50: {
      emabled: false,
      prct: "50%",
      xAxis: "0",
      yAxis: "0",
      transform: {
        rotate: "110deg",
        scale: "1.0",
        translate: "0deg, 0deg",
        skew: "0deg, 0deg",
      },
      filter: {
        blur: "0px",
        brightness: "0.0",
        contrast: "0%",
        greyscale: "0%",
        hueRotate: "0deg",
        dropShadow: "0px 0px 0px black",
        invert: "0%",
        opacity: "0%",
        saturate: "0%",
        sepia: "0%",
      }
    },
    prct60: {
      emabled: false,
      prct: "60%",
      xAxis: "0",
      yAxis: "0",
      transform: {
        rotate: "110deg",
        scale: "1.0",
        translate: "0deg, 0deg",
        skew: "0deg, 0deg",
      },
      filter: {
        blur: "0px",
        brightness: "0.0",
        contrast: "0%",
        greyscale: "0%",
        hueRotate: "0deg",
        dropShadow: "0px 0px 0px black",
        invert: "0%",
        opacity: "0%",
        saturate: "0%",
        sepia: "0%",
      }
    },
    prct70: {
      emabled: false,
      prct: "70%",
      xAxis: "0",
      yAxis: "0",
      transform: {
        rotate: "110deg",
        scale: "1.0",
        translate: "0deg, 0deg",
        skew: "0deg, 0deg",
      },
      filter: {
        blur: "0px",
        brightness: "0.0",
        contrast: "0%",
        greyscale: "0%",
        hueRotate: "0deg",
        dropShadow: "0px 0px 0px black",
        invert: "0%",
        opacity: "0%",
        saturate: "0%",
        sepia: "0%",
      }
    },
    prct80: {
      emabled: false,
      prct: "80%",
      xAxis: "0",
      yAxis: "0",
      transform: {
        rotate: "110deg",
        scale: "1.0",
        translate: "0deg, 0deg",
        skew: "0deg, 0deg",
      },
      filter: {
        blur: "0px",
        brightness: "0.0",
        contrast: "0%",
        greyscale: "0%",
        hueRotate: "0deg",
        dropShadow: "0px 0px 0px black",
        invert: "0%",
        opacity: "0%",
        saturate: "0%",
        sepia: "0%",
      }
    },
    prct90: {
      emabled: false,
      prct: "90%",
      xAxis: "0",
      yAxis: "0",
      transform: {
        rotate: "110deg",
        scale: "1.0",
        translate: "0deg, 0deg",
        skew: "0deg, 0deg",
      },
      filter: {
        blur: "0px",
        brightness: "0.0",
        contrast: "0%",
        greyscale: "0%",
        hueRotate: "0deg",
        dropShadow: "0px 0px 0px black",
        invert: "0%",
        opacity: "0%",
        saturate: "0%",
        sepia: "0%",
      }
    },
    prct100: {
      enabled: true,
      prct: "100%",
      xAxis: "0",
      yAxis: "0",
      transform: {
        rotate: "110deg",
        scale: "1.0",
        translate: "0deg, 0deg",
        skew: "0deg, 0deg",
      },
      filter: {
        blur: "0px",
        brightness: "0.0",
        contrast: "0%",
        greyscale: "0%",
        hueRotate: "0deg",
        dropShadow: "0px 0px 0px black",
        invert: "0%",
        opacity: "0%",
        saturate: "0%",
        sepia: "0%",
      }
    }
  }